name: Skyblock
version: '${project.version}'
main: com.sweattypalms.skyblock.SkyBlock
api-version: "1.13"
authors: [ sweattypalms, devil_gamer_xd, shlok ]
description: A Hypixel Skyblock remake plugin
website: sweattypalms.me
softdepend:
  - Multiverse-Core
commands:
  wtf:
    description: WTF
